swagger: "2.0"
info:
  description: "Dybov's and Lavrov's blse lab"
  title: "Rubbable api"
  version: "1.0.0"


host: "localhost:8000"
basePath: "/api"

schemes:
- "http"
paths:
  /users/me/:
    get:
      description: "Get self user profile info"
      produces:
      - "application/json"
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/UserDto"
          
  /teams/:
    get:
      description: "Get teams list"
      produces:
      - "application/json"
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true
        
      responses:
        "200":
          description: "user found"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TeamDto"
        "400":
          description: "Validation Error"
          schema:
            type: string
            
  /teams/{id}/:
    get:
      description: "Get team by id"
      produces:
      - "application/json"
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true
      
      - name: id
        in: path
        type: integer
        required: true
        
      responses:
        "200":
          description: "user found"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TeamDto"

    

  /tournaments/:
    get:
      description: "Get all tournaments"
      produces:
      - "application/json"
      
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true

      responses:
        "200":
          description: "List of tournaments"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ListTournamentDto"
    
    post:
      description: "Create new tournament. 1 <= maxGames, judges.length <= 10, maxGames % 2 == 1"
      produces:
      - "application/json"
      
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true
      - name: body
        in: body
        schema: 
          $ref: "#/definitions/CreateTournamentDto"
        

      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/RetrieveTournamentDto"
            
        "400":
          description: "Validation Error"
          schema:
            type: string
  
  /games/{game-id}/approve/:
    post:
      description: "Approve game"
      produces:
      - "application/json"
      
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true
      - name: game-id
        in: path
        type: integer
        required: true
        

      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/GameDto"
            
        "400":
          description: "Validation Error"
          schema:
            type: string
  
  /games/{game-id}/disapprove/:
    post:
      description: "Disapprove game"
      produces:
      - "application/json"
      
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true
      - name: game-id
        in: path
        type: integer
        required: true
        

      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/GameDto"
            
        "400":
          description: "Validation Error"
          schema:
            type: string
  
  /matches/{match-id}/play-game/:
    post:
      description: "Add game to match"
      produces:
      - "application/json"
      
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true
      - name: match-id
        in: path
        type: integer
        required: true
      
      - name: winnerId
        in: query
        type: integer
        required: true
        

      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/MatchDto"
            
        "400":
          description: "Validation Error"
          schema:
            type: string
            
  /matches/{match-id}/drop/:
    post:
      description: "Drop match games"
      produces:
      - "application/json"
      
      parameters:
      - name: user-id
        type: integer
        in: header
        required: true
      - name: match-id
        in: path
        type: integer
        required: true
      
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/RetrieveTournamentDto"
            
        "400":
          description: "Validation Error"
          schema:
            type: string  
  
  

definitions:
  UserDto:
    type: "object"
    properties:
      id:
        type: "integer"
      username:
        type: "string"

  
  TeamDto:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        
  ListTournamentDto:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      startDate:
        type: "string"
      approvalRatio:
        type: "number"
      maxGames:
        type: "integer"
  
  
  GameVoteDto:
    type: "object"
    properties:
      id:
        type: "integer"
      judgeId:
        type: "integer"
      isApproved:
        type: "boolean"
  
  GameDto:
    type: "object"
    properties:
      id:
        type: "integer"
      winnerId:
        type: "integer"
      gameVotes:
        type: "array"
        items:
          $ref: "#/definitions/GameVoteDto"
        
  MatchDto:
    type: "object"
    properties:
      id:
        type: "integer"
      team1Id:
        type: "integer"
      team2Id:
        type: "integer"
      nextMatchId:
        type: "integer"
      games:
        type: "array"
        items:
          $ref: "#/definitions/GameDto"
    
  
  RetrieveTournamentDto:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      startDate:
        type: "string"
      approvalRatio:
        type: "number"
      maxGames:
        type: "integer"
      judges:
        type: "array"
        items:
          $ref: "#/definitions/UserDto"
      teams:
        type: "array"
        items:
          $ref: "#/definitions/TeamDto"
      matches:
        type: "array"
        items:
          $ref: "#/definitions/MatchDto"
  
  CreateTournamentDto:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      startDate:
        type: "string"
      approvalRatio:
        type: "number"
      maxGames:
        type: "integer"
      judgesIds:
        type: "array"
        items:
          type: "integer"
      teamsIds:
        type: "array"
        items:
          type: "integer"

      
  


